# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW...
# nombre del filtro a usar: 'following.'
    following.twig_extension:
        class: AppBundle\Twig\FollowingExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE CUANTO TIEMPO HACE...
# nombre del filtro a usar: 'long_time'
    long_time.twig_extension:
        class: AppBundle\Twig\LongTimeExtension
        public: false
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE CUANTO TIEMPO HACE
