# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW...
    # nombre del filtro a usar: 'following.'
    following.twig_extension:
        class: AppBundle\Twig\FollowingExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE CUANTO TIEMPO HACE...
    # nombre del filtro a usar: 'long_time'
    long_time.twig_extension:
        class: AppBundle\Twig\LongTimeExtension
        public: false
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE CUANTO TIEMPO HACE
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW...
    # nombre del filtro a usar: 'liked'
    liked.twig_extension:
        class: AppBundle\Twig\LikedExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE FOLLOW AND UNFOLLOW
# EXTENSIÓN DE TWIG PARA EL SISTEMA DE ESTADÍSTICAS DEL USUARIO...
    # nombre del filtro a usar: 'users_stats'
    users_stats.twig_extension:
        class: AppBundle\Twig\UserStatsExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA EL SISTEMA DE ESTADÍSTICAS DEL USUARIO
# EXTENSIÓN DE TWIG PARA OBTENER EL OBJETO USER A PARTIR DE SU ID...
    # nombre del filtro a usar: 'get_user'
    get_user.twig_extension:
        class: AppBundle\Twig\GetUserExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# ...EXTENSIÓN DE TWIG PARA OBTENER EL OBJETO USER A PARTIR DE SU ID
# EXTENSIÓN SERVICIO DE NOTIFICACIONES...
    app.notification_service:
        class: AppBundle\Services\NotificationService
        arguments: ["@doctrine.orm.entity_manager"]
# ...EXTENSIÓN SERVICIO DE NOTIFICACIONES
