# ROUTING PARA CONSULTA AJAX (SEGUIR)
following_follow:
    path: /follow
    defaults: { _controller: AppBundle:Following:follow }
    methods: [POST]
# ROUTING PARA CONSULTA AJAX (DEJAR DE SEGUIR)
following_unfollow:
    path: /unfollow
    defaults: { _controller: AppBundle:Following:unfollow }
    methods: [POST]
# ROUTING PARA HOME PUBLICATION MUESTRA USUARIOS QUE SIGUE EL USUARIO
following_users:
    path: /following/{nickname}
    defaults: { _controller: AppBundle:Following:following, nickname:null }
# ROUTING PARA HOME PUBLICATION MUESTRA USUARIOS QUE SIGUEN AL USUARIO
followed_users:
    path: /followed/{nickname}
    defaults: { _controller: AppBundle:Following:followed, nickname:null }
