# ROUTING PARA CONSULTA AJAX (SEGUIR)
following_follow:
    path: /follow
    defaults: { _controller: AppBundle:Following:follow }
    methods: [POST]
# ROUTING PARA CONSULTA AJAX (DEJAR DE SEGUIR)
following_unfollow:
    path: /unfollow
    defaults: { _controller: AppBundle:Following:unfollow }
    methods: [POST]
