# ROUTING PARA PÁGINA DE MENSAJES PRIVADOS
private_message_index:
    path: /private-message
    defaults: { _controller: AppBundle:PrivateMessage:index }
# ROUTING PARA PÁGINA DE MENSAJES ENVIADOS
private_message_sended:
    path: /private-message/sended
    defaults: { _controller: AppBundle:PrivateMessage:sended }
# ROUTING PARA CONSULTA AJAX (GENERAR ALERTAS MENSAJES)
private_message_notification:
    path: /private-message/notification/get
    defaults: { _controller: AppBundle:PrivateMessage:notReaded }
