# DIRECCIÓN ROUTING PARA HOME
app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
# DIRECCIÓN ROUTING PARA USER
app_user:
    resource: '@AppBundle/Resources/config/routing/user.yml'
    prefix:   /
# DIRECCIÓN ROUTING PARA PUBLICATION
app_publication:
    resource: '@AppBundle/Resources/config/routing/publication.yml'
    prefix:   /
# DIRECCIÓN ROUTING PARA FOLLOWING
app_following:
    resource: '@AppBundle/Resources/config/routing/following.yml'
    prefix:   /
# DIRECCIÓN ROUTING PARA LIKE de PUBLICACIONES
app_like:
    resource: '@AppBundle/Resources/config/routing/like.yml'
    prefix:   /
# DIRECCIÓN ROUTING PARA NOTIFICACIONES GENERALES
app_notification:
    resource: "@AppBundle/Resources/config/routing/notification.yml"
    prefix: /
# DIRECCIÓN ROUTING PARA NOTIFICACIONES MENSAJES
app_private_message:
    resource: "@AppBundle/Resources/config/routing/private_message.yml"
    prefix: /
